services:
  app:
    build: .
    env_file:
      - .env 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/logs
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all